import type { Metadata } from "next";
import "./globals.css";
import { Menu } from "@/components/menu";

import {
  TooltipProvider
} from "@/components/ui/tooltip"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <TooltipProvider>
          <div className="flex min-h-screen w-full flex-col bg-muted/40">
            <aside className="fixed inset-y-0 left-0 z-10 hidden w-14 flex-col border-r bg-background sm:flex">
              < Menu/>
            </aside>
            <div style={{paddingLeft: "50px", paddingTop: "50px"}}>
            {children}
            </div> 
          </div>   
        </TooltipProvider>
      </body>
    </html>
  );
}
